name: Release

on:
  push:
    branches: master

jobs:
  create-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure rust
        run: rustup default nightly
        
      - name: Configure rust
        run: rustup override set nightly

      - name: Build
        run: cargo build --release

      - name: Bump version and push tag/create release point
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
        id: bump_version

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/clipboard-sync-rs.exe
          asset_name: clipboard-sync-rs.exe
          tag: ${{ steps.bump_version.outputs.new_tag }}
          overwrite: true
